### PR TITLE
Move chat to matrix

### PR DESCRIPTION
**Pull request by jgraham**
[Rendered](https://github.com/web-platform-tests/rfcs/blob/matrix/rfcs/matrix.md)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Support.

**Comment by foolip** [comment]
Great write up, and I'm very supportive of the move. I hadn't ever used Element before and other than a little dance to log into multiple devices, it's just felt very polished, a big improvement to IRC.

**Comment by jgraham** [comment]
https://github.com/web-platform-tests/wpt/pull/29484 for the documentation update.

I believe that per the process this should be considered approved (it's also de-facto true that discussion is now happening on matrix), but it would be good to get it marked as approved before merging.

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
@jgraham approved, but did you mean some other kind of approval than code review?

**Review by Ms2ger — APPROVED** [review]

**Comment by jgraham** [comment]
Just code review :)

**Pull request merged**
