### PR TITLE
Document that no RFC is needed for most testdriver.js additions

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Review by Ms2ger — APPROVED** [review]
Fine by me

**Comment by jgraham** [comment]
I think we decided that this should itself be an RFC.

**Comment by foolip** [comment]
@past agreed to turn it into a RFC. It's pretty much this language, plus stating that there should be tests.

**Comment by jcscottiii** [comment]
@foolip Now that #127 is merged, this can be merged. Are there any remaining changes to this PR?

**Pull request merged**
