### PR TITLE
RFC 44: testing origin policy

### PR DESCRIPTION
**Pull request by domenic**
[Rendered](https://github.com/domenic/rfcs/blob/patch-1/rfcs/origin_policy.md)

### CODE REVIEW

**Comment by zcorpan** [comment]
This looks good to me, but is there a downside to using a greater number of subdomains from the start (like 99)? I'm thinking that there may be some churn to changing the subdomains, so it's better to do it fewer times and end up with more subdomains than we need, than to change them multiple times.

**Comment by domenic** [comment]
Yeah, I think you're right; that'd probably be a better place to start. I will update the RFC and pull request.

**Comment by jgraham** [comment]
Is there a requirement that each test uses a different origin? Do we have some way to enforce/lint for that?

**Comment by domenic** [comment]
No, it's not. As long as the tests are careful to test non-overlapping features, they can share. You can see some examples of that in https://github.com/web-platform-tests/wpt/pull/21739 (which was for some reason closed....)

**Comment by jgraham** [comment]
Hmm, having to be careful about testing non-overlapping features makes me nervous about conflicts between apparently unrelated tests (e.g. if two authors write tests at the same time for the same feature). However given that we can't make a wildcard certificate I don't currently have any good ideas for improvements here.

**Comment by domenic** [comment]
OK, cool! It looks like it's been 7 days; would we be able to merge this---and more importantly, https://github.com/web-platform-tests/wpt/pull/21705 --- now?

**Comment by gsnedders** [comment]
Note we previously had problems on Windows where IIRC we end up with all the hosts in an environment variable and this might take us over the maximum length of a variable.

**Comment by domenic** [comment]
@gsnedders yes, that was dealt with in https://github.com/web-platform-tests/wpt/pull/21705#issuecomment-587578635

**Pull request merged**
