### PR TITLE
RFC 173 - Use @page for print refests

### PR DESCRIPTION
**Pull request by jgraham**

### CODE REVIEW

**Review by jwatt — APPROVED** [review]
Yes, please.

**Review by foolip — APPROVED** [review]
I've confirmed with @mstensho that this makes sense for Chrome.

**Comment by foolip** [comment]
@past FYI, I approved this.

**Comment by mstensho** [comment]
Now is a good time to ping on https://github.com/web-platform-tests/wpt/issues/40788 - we have https://web-platform-tests.org/writing-tests/print-reftests.html which says nothing about the 0.5 inch margins. Can this documentation be updated, or removed? This is the documentation I got to when searching, and I wasn't even aware of https://github.com/web-platform-tests/rfcs/blob/master/rfcs/print_test.md .

**Review by Ruben-VandeVelde — APPROVED** [review]

**Pull request merged**
