### PR TITLE
RFC 17 - Code of Conduct

### PR DESCRIPTION
**Pull request by jugglinmike**
In [WPT issue gh-7520](https://github.com/web-platform-tests/wpt/pull/7520), @plehegar made an initial attemp to introduce a code of conduct based on the Rust language's policy. That seems like a good place to start from since it was only blocked on the existence of a group like the WPT Core Team. Should the code itself be included in this RFC?

One detail that needs to be decided is if the WPT Core Team is to be the same as the group of enforcers. Whatever the case, we should have some public commitment from each person who is listed in that document.

[Here's the rendered version.](https://github.com/bocoup/wpt-rfcs/blob/code-of-conduct/rfcs/code_of_conduct.md)

### CODE REVIEW

**Comment by gsnedders** [comment]
> Should the code itself be included in this RFC?

Probably yes.

> One detail that needs to be decided is if the WPT Core Team is to be the same as the group of enforcers. 

I think both myself and @jgraham, per discussion on IRC earlier, strongly feel that it *must not* be. Otherwise if the question is about the conduct of the Core Team (in whole or in part) is in question, then the same group are trying to resolve it.

As I said earlier, I'd quite strongly prefer to have a more diverse set of individuals than the Core Team (really I'd rather that be more diverse too!), given plenty of conflict can be down to mistreatment of minority groups, and it helps to have people they feel will understand their concerns (and the almost entirely cis white men of the Core Team aren't that). That said, to do this will likely involve reaching out to people in browser communities that aren't so involved with standards or this project upstream (both of which are notably less diverse than the browser communities as a whole).

**Comment by foolip** [comment]
@jugglinmike can you propose changes for https://github.com/web-platform-tests/wpt/pull/7520 to make this more concrete?

**Comment by jugglinmike** [comment]
@foolip The only change I have in mind is designating the makeup of the enforcement team. Based on @gsnedders' and @jgraham's input, that will require a concerted effort. It may be premature to discuss this as an RFC, so in recognition of [the process's "accept by default" design](https://github.com/web-platform-tests/rfcs/blob/ed0d288e4aaf8a66df608fb97dd7a9f63310c1bb/README.md#the-rfc-process), I'll close it for now. I've opened gh-21 in the hopes that we can continue to make forward progress.

**Comment by boazsender** [comment]
I just submitted a patch to @plehegar original PR adding myself and @jorydotcom to the enforcement list. I suggest reopening this PR and merging it in here to serve as a final decision behind merging the CoC patches into WPT (https://github.com/web-platform-tests/wpt/pull/18950 & https://github.com/web-platform-tests/wpt/pull/7520),

**Comment by foolip** [comment]
Reopening. @web-platform-tests/wpt-core-team per our process we should leave one week for comments, which would mean resolving this during TPAC. We can discuss there too if needed.

**Comment by foolip** [comment]
@jugglinmike what's the state of this now? Came here because https://github.com/web-platform-tests/wpt/pull/7520 was assigned to me, assigned that to you instead :)

**Comment by jugglinmike** [comment]
@foolip I closed this and filed gh-21 as a prerequisite. That issue remains open, so I don't have anything new to add. @boazsender [requested](https://github.com/web-platform-tests/rfcs/issues/21#issuecomment-529734574) that this issue be assigned to him. I'm unable to do this; would you mind?

[Boaz also made some modifications to gh-7520](https://github.com/web-platform-tests/wpt/pull/18948), so it may be appropriate to assign that to him as well.

**Comment by foolip** [comment]
@jugglinmike sure, I'll assign those to Boaz.

**Comment by thejohnjansen** [comment]
Hey everyone... where are we with this? This is the first step required before I can push the "editor" site out to its new domain. Is there anything still blocking here, or just waiting for a "LGTM" from everyone?

**Comment by boazsender** [comment]
Thanks for bumping, and sorry for the delay. The next steps I have are to:
* Suggest in process for volunteering CoC moderator group to WPT
* Define enforcement guidelines

I've blocked off working time to make these proposals this on Thursday and will follow up then.

**Comment by jgraham** [comment]
What's the status here? Is anyone working on this issue?

**Comment by boazsender** [comment]
Continued apologies for the delay. I haven't been able to prioritize time to write the additional policy. I will look into getting time for this this month.

**Comment by boazsender** [comment]
Hi folks,
Its been six months and I haven't been able to work on enforcement guidelines or the process for adding new moderators.

Does anyone else on this thread have bandwidth to work on this, or know anyone with resources to support this work?

**Comment by stephenmcgruer** [comment]
Thanks Boaz; it can be hard to take the step back and acknowledge when one is overloaded, but it's also important so I appreciate you doing so :)

I have laid out what I believe the next steps are in the tracking issue (https://github.com/web-platform-tests/rfcs/issues/21#issuecomment-615283331) for this RFC. I think we should strive to keep discussion in that issue until we have a concrete proposal for the RFC.

**Comment by stephenmcgruer** [comment]
Closing in favor of https://github.com/web-platform-tests/rfcs/pull/54, due to issues with editing this cross-fork PR.

**Pull request closed without merging**
