### PR TITLE
Allow unrestricted Promise usage in testharness.js

### PR DESCRIPTION
**Pull request by jgraham**

### CODE REVIEW

**Review by zcorpan — APPROVED** [review]

**Comment by annevk** [comment]
I was hoping for a policy that would have this as a side effect, but perhaps it's good to decide on this individually as well.

**Comment by jgraham** [comment]
Yes, #92 is about overall policy, but this seems like low hanging fruit so worth splitting out into a smaller item.

https://github.com/web-platform-tests/wpt/pull/29985 is a PR with the actual code changes to remove the support for testing testharness without the Promise constructor.

**Review by foolip — APPROVED** [review]

**Review by Ms2ger — APPROVED** [review]

**Comment by Ms2ger** [comment]
Ping @louaybassbouss about the WAVE comment in particular

**Comment by louaybassbouss** [comment]
> Ping @louaybassbouss about the WAVE comment in particular

Thanks @Ms2ger  for pinging me let me check I will ASAP to you.

**Comment by jgraham** [comment]
@louaybassbouss do you have an update here, or can we go ahead and merge this?

**Review by foolip — APPROVED** [review]

**Comment by FritzHeiden** [comment]
> @louaybassbouss do you have an update here, or can we go ahead and merge this?

Looks good, go ahead and merge

**Comment by foolip** [comment]
It looks like the test cleanup for this never happened, so actually adding dependencies on Promise is still hard. I've sent https://github.com/web-platform-tests/wpt/pull/33507.

**Pull request merged**
