### PR TITLE
RFC: Remove support for stub-* files in the manifest

### PR DESCRIPTION
**Pull request by foolip**
[Rendered](https://github.com/web-platform-tests/rfcs/blob/foolip/remove_stub/rfcs/remove_stub.md)

### CODE REVIEW

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/18744 shows all the code that would be removed, but I intend to split it into two changes as per the RFC.

**Comment by jgraham** [comment]
Sounds great. This idea didn't work out so I'm happy to remove support.

**Comment by foolip** [comment]
Draft PRs:
- [Remove service-workers/stub-* files](https://github.com/web-platform-tests/wpt/pull/18745)
- [Remove support for stub-* files in the manifest](https://github.com/web-platform-tests/wpt/pull/18746)

Paging SW reviewers @asutherland @mkruisselbrink @mattto @wanderview, are you all OK with this cleanup?

**Comment by mattto** [comment]
Yes, as far as I know we never ran the stubs for Chromium and I never heard of anyone working on them.

**Comment by foolip** [comment]
Thanks @mattto, I'll take that as support for https://github.com/web-platform-tests/wpt/pull/18745. Since @jgraham has already reviewed that and it's cleanup that by itself wouldn't go through the RFC process, I'll merge that now. It'll be good to put some time between that and the manifest change.

**Comment by foolip** [comment]
Alright, I consider this passed, I'll merge it and finish https://github.com/web-platform-tests/wpt/pull/18746.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/18746 has also been merged now, so this is done. Thanks all!

**Pull request merged**
