### PR TITLE
RFC 158# Do not allow zero length variant names

### PR DESCRIPTION
**Pull request by WeizhongX**

### CODE REVIEW

**Comment by WeizhongX** [comment]
@jgraham @gsnedders @past can you guys pls take a look? thanks!

**Comment by WeizhongX** [comment]
> How many tests currently use zero-length variants?

There are about 200 tests (js or html) use zero-length variants, and they are mostly in websockets and navigation-api.

**Comment by WeizhongX** [comment]
Hey @jcscottiii, can you also pls take a look? Thanks!

**Review by jgraham — APPROVED** [review]
I think this is OK.

For me the main argument against using `?` or `#` to indicate a zero length variant is how many libraries don't distinguish between "this has a query/fragment, but it's empty" and "this doesn't have a query/fragment". The URL spec does make the distinction, so I don't think there's a principled reason we couldn't depend on it, but it might be surprising and hard to implement. Meanwhile making people name each variant does seem like it adds a little extra documentation.

**Review by jcscottiii — APPROVED** [review]

**Comment by WeizhongX** [comment]
@jcscottiii , I do not have write access, so can you help merge this one (if it is ready)? thanks!

**Pull request merged**
