### PR TITLE
RFC 149: Support reftest variants

### PR DESCRIPTION
**Pull request by dlrobertson**
Add support for variants when writing reftests.

[Rendered](https://github.com/dlrobertson/wpt-rfcs/blob/reftest-variants/rfcs/reftest_variants.md)

Initial implementation: https://github.com/web-platform-tests/wpt/pull/40352

### CODE REVIEW

**Comment by dlrobertson** [comment]
CC @jgraham

**Comment by dlrobertson** [comment]
😆 should have double checked which RFC number this would be

**Comment by Ms2ger** [comment]
> > I think the examples in this RFC are simplified too much to be convincing, but agree that the overall idea makes sense.
> 
> Good point. My intent was to stick to a well known example. Do you think it is worthwhile to create a more complex example with more parameters?

I think it's probably fine

**Comment by jcscottiii** [comment]
As discussed in the last infra [meeting](https://github.com/web-platform-tests/wpt-notes/blob/master/minutes/2023-06-06.md#rfc-149-support-reftest-variants-link), we will merge this.

**Pull request merged**
