### PR TITLE
RFC 72: Use port-based overrides instead.

### PR DESCRIPTION
**Pull request by letitz**
As discussed in #79.

@ddragana gave the thumbs-up in https://github.com/web-platform-tests/rfcs/issues/79#issuecomment-832629726.

### CODE REVIEW

**Comment by ddragana** [comment]
This looks good.

**Comment by letitz** [comment]
@foolip @jgraham for visibility.

**Review by jgraham — APPROVED** [review]

**Comment by letitz** [comment]
What's the next step here?

**Comment by letitz** [comment]
@jgraham friendly ping. Were we waiting for last-minute objections?

**Pull request merged**
