### PR TITLE
RFC 182: Add WebDriver BiDi support to testdriver.js

### PR DESCRIPTION
**Pull request by sadym-chromium**
Add “testdriver.js” support for [WebDriver BiDi](https://w3c.github.io/webdriver-bidi/) events and actions.

***
<a href="https://github.com/sadym-chromium/wpt_rfcs/blob/sadym/testdriver-bidi/rfcs/testdriver_bidi.md" title="Latest version">Preview</a>

### CODE REVIEW

**Comment by sadym-chromium** [comment]
@jgraham @gsnedders friendly ping

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
Given no feedback in 3 weeks this RFC has passed an I'll go ahead and merge it.

Feedback on the implementation and experience writing tests with this will probably require some additional changes, but I trust we can figure that out. I'm quite excited to see BiDi used to improve WPT testing capabilities, and want to see the next phase of this.

**Comment by jgraham** [comment]
I'm not happy with the unilateral merge here. This was brought up at the last infra meeting and there was a commitment to give feedback. Although I appreciate the letter of the process allows this, I don't think such unilateral action is in the spirit of collaboration, even though I understand that there can be frustration when people's internal priorities are blocked on community feedback. I'm going to revert this change and we can discuss further.

**Comment by jgraham** [comment]
Reverted via https://github.com/web-platform-tests/rfcs/pull/184 Unfortunately you'll need to create a PR to continue this RFC.

**Comment by foolip** [comment]
> I'm not happy with the unilateral merge here. This was brought up at the last infra meeting and there was a commitment to give feedback. Although I appreciate the letter of the process allows this, I don't think such unilateral action is in the spirit of collaboration, even though I understand that there can be frustration when people's internal priorities are blocked on community feedback. I'm going to revert this change and we can discuss further.

I was not in that meeting, so I didn't know about those commitments. Expedient review of https://github.com/web-platform-tests/rfcs/pull/185 would be much appreciated.

On the process, it has a timeout in the absence of feedback for a reason, and I would expect it to be used by others if Google doesn't provide any feedback too.

**Comment by foolip** [comment]
I've filed https://github.com/web-platform-tests/rfcs/issues/187 because the revert was outside of our documented process.

**Comment by sadym-chromium** [comment]
@jgraham I'm sorry for the miscommunication happened on the meeting. I got the silence as "let's experiment with the proposed solution, and we can figure out details on the implementation stage".

**Pull request merged**
